export const mockTicketsArray = [
	{
		id: "1234567",
		title: "Erro ao carregar relatórios",
		creator: "João Silva",
		status: "Aberto",
		date: new Date("2025-01-01"),
		description: "Relatórios na página do painel demoram para carregar ou não carregam. Usuários reportam impacto em suas tarefas diárias.",
		comentaries: [
			{ author: "João Silva", comment: "Primeiro relato ocorreu ontem à tarde." },
			{ author: "João Silva", comment: "Logs indicam timeout na API de relatórios." },
			{ author: "João Silva", comment: "Banco de dados parece estar operando normalmente." },
		],
	},
	{
		id: "2345678",
		title: "Problemas no login com autenticação social",
		creator: "Maria Oliveira",
		status: "Em Andamento",
		date: new Date("2025-01-02"),
		description: "Usuários não conseguem realizar login utilizando redes sociais. O erro persiste em várias plataformas.",
		comentaries: [
			{ author: "Maria Oliveira", comment: "Reproduzi o erro com login via Google." },
			{ author: "Maria Oliveira", comment: "Verifiquei a integração e há falhas na autenticação OAuth." },
		],
	},
	{
		id: "3456789",
		title: "Solicitação de novo recurso: Filtro avançado",
		creator: "Carlos Pereira",
		status: "Concluído",
		date: new Date("2024-12-28"),
		description: "Os usuários pedem filtros avançados para a pesquisa, incluindo busca por data, status e tags.",
		comentaries: [
			{ author: "Carlos Pereira", comment: "Funcionalidade testada e validada com sucesso." },
			{ author: "Carlos Pereira", comment: "Implementado na versão 2.3.0, disponível no ambiente de produção." },
		],
	},
	{
		id: "4567890",
		title: "Notificações por e-mail não enviadas",
		creator: "Ana Costa",
		status: "Aberto",
		date: new Date("2025-01-03"),
		description: "Atualizações em pedidos ou mudanças de status não estão gerando notificações por e-mail para os usuários.",
		comentaries: [
			{ author: "Ana Costa", comment: "Serviço de e-mail foi reiniciado, mas o problema persiste." },
			{ author: "Ana Costa", comment: "Configurações do servidor de e-mail verificadas sem alterações recentes." },
		],
	},
	{
		id: "5678901",
		title: "Lentidão ao acessar a página inicial",
		creator: "Rafael Nogueira",
		status: "Em Andamento",
		date: new Date("2025-01-04"),
		description: "A página inicial demora mais de 10 segundos para carregar após a última atualização.",
		comentaries: [
			{ author: "Rafael Nogueira", comment: "O problema parece ocorrer apenas em conexões móveis." },
			{ author: "Rafael Nogueira", comment: "Possível relação com arquivos estáticos não otimizados." },
		],
	},
	{
		id: "6789012",
		title: "Erro de tradução em espanhol",
		creator: "Paula Souza",
		status: "Aberto",
		date: new Date("2025-01-05"),
		description: "Algumas palavras no sistema não estão traduzidas corretamente para o idioma espanhol, especialmente no módulo de relatórios.",
		comentaries: [{ author: "Paula Souza", comment: "Tradução incorreta identificada na seção de relatórios." }],
	},
	{
		id: "7890123",
		title: "Problemas no cálculo de preços com desconto",
		creator: "Rodrigo Santos",
		status: "Concluído",
		date: new Date("2024-12-30"),
		description: "O sistema aplica descontos incorretamente em compras com grande quantidade de itens.",
		comentaries: [{ author: "Rodrigo Santos", comment: "Bug corrigido e validado no ambiente de produção." }],
	},
	{
		id: "8901234",
		title: "Aplicativo travando no iOS",
		creator: "Beatriz Almeida",
		status: "Aberto",
		date: new Date("2025-01-06"),
		description: "O aplicativo trava ao acessar o perfil de usuário em dispositivos iOS, mesmo com as versões mais recentes do sistema.",
		comentaries: [
			{ author: "Beatriz Almeida", comment: "O problema foi reportado em iPhones e iPads." },
			{ author: "Beatriz Almeida", comment: "Logs indicam falha ao carregar imagens de perfil." },
		],
	},
	{
		id: "9012345",
		title: "Revisão na política de senha",
		creator: "Fernanda Lima",
		status: "Aberto",
		date: new Date("2025-01-07"),
		description:
			"O sistema permite que usuários criem senhas fracas, o que compromete a segurança. É necessário implementar requisitos mais rigorosos.",
		comentaries: [
			{ author: "Fernanda Lima", comment: "Sugestão: exigir pelo menos 8 caracteres, com letras, números e símbolos." },
			{ author: "Fernanda Lima", comment: "Pontos de vulnerabilidade identificados em testes de segurança." },
		],
	},
	{
		id: "0123456",
		title: "API de relatórios desatualizada",
		creator: "Gustavo Rocha",
		status: "Em Andamento",
		date: new Date("2025-01-06"),
		description: "A documentação da API não reflete as mudanças feitas na última atualização, causando confusão para desenvolvedores externos.",
		comentaries: [{ author: "Gustavo Rocha", comment: "Revisão de documentação está em andamento." }],
	},
];
